# Generated by Django 4.1.7 on 2023-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=100, verbose_name='首页标题')),
                ('home_title_en', models.CharField(max_length=100, null=True, verbose_name='首页标题')),
                ('home_title_zh_hans', models.CharField(max_length=100, null=True, verbose_name='首页标题')),
                ('home_bg', models.ImageField(upload_to='home_background/', verbose_name='首页图片')),
            ],
        ),
    ]
